Esercizio3
Antonioverrastro/Angular_def pull request #3
Opened 2021-11-09 15:29 UTC by Antonioverrastro

2021-11-19 11:13 UTC, Giulia-Reas requested changes

2021-11-19 11:13 UTC, Giulia-Reas commented on app/src/app/models/objects.ts
> +export interface Companies {
un interfaccia dovrebbe essere singolare

2021-11-19 11:13 UTC, Giulia-Reas commented on app/src/app/user-detail/user-detail/user-detail.component.ts
> +  utente = user;
non usare due lingue e in generale usa solo l'inglese per variabili, funzioni, etc..

2021-11-19 11:13 UTC, Giulia-Reas commented on app/src/app/user-list/user-list/user-list.component.ts
> +export interface Obj {
perchè hai riscritto le interfacce?

2021-11-19 11:13 UTC, Giulia-Reas commented on app/src/app/user-single/user-single/user-single.component.ts
> +import { Component, Input, OnInit } from '@angular/core';
questo Input non viene utilizzato

2021-11-19 11:43 UTC, Giulia-Reas commented
hai dei conflitti, devi risolverli in locale, così non puoi effettuare il merge

2021-11-23 15:59 UTC, Giulia-Reas requested changes

2021-11-23 15:59 UTC, Giulia-Reas commented on app/src/app/user-detail/user-detail/user-detail.component.ts
> +export const user : User  = {
riportalo al suo posto!

2021-11-23 15:59 UTC, Giulia-Reas commented on app/src/app/user-detail/user-detail/user-detail.component.html
> +  <!-- <p>id: {{user.id}}</p>
leva il commento

2021-11-23 16:05 UTC, Antonioverrastro commented on app/src/app/user-detail/user-detail/user-detail.component.html
> +  <!-- <p>id: {{user.id}}</p>
Eliminato

2021-11-23 16:05 UTC, Antonioverrastro commented on app/src/app/user-detail/user-detail/user-detail.component.ts
> +export const user : User  = {
Riportato al posto giusto

2021-11-26 16:01 UTC, Giulia-Reas approved these changes

2021-11-26 16:01 UTC, merged